OffchainLabs/stylus-sdk-rs

- stylus-proc/src/types.rs
- stylus-sdk/src/abi/fixed_bytes.rs
- stylus-sdk/src/abi/impls.rs
- stylus-sdk/src/abi/mod.rs
This PR removes our custom `FixedBytes` type in favor of Alloy's. Ideally we'd also drop `FixedBytesSolType`, but that'd require upstream update the corresponding `SolType` implementation.
- https://github.com/alloy-rs/core/issues/259
This is a breaking change and will require a version bump to `0.2.0`.
This will allow one to more easily do the following without importing a second `FixedBytes` type.
```rs
pub fn root(&self) -> Result<B256, Vec<u8>> {
Ok(self.root.get().into())
}
```
> Simplify fixed bytes

- Cargo.lock
- Cargo.toml
- stylus-proc/src/calls/mod.rs
- stylus-sdk/Cargo.toml
Fixes `sol_interface!` when given expanding args. 
We'd mistakenly expanded it to `(,)`, rather than `()`.
```rs
sol_interface! {
interface IClass {
function empty();
}
}
```
Solves: #44
> Fix `sol_interface!` when expanding empty args

- stylus-sdk/src/block.rs
- stylus-sdk/src/call/raw.rs
- stylus-sdk/src/contract.rs
- stylus-sdk/src/deploy/raw.rs
- stylus-sdk/src/hostio.rs
- stylus-sdk/src/msg.rs
- stylus-sdk/src/tx.rs
Equivalent to the following, which was based on a much older version of the SDK
- #16
> Implement hostio caching

- stylus-sdk/Cargo.toml
- stylus-sdk/src/call/mod.rs
- stylus-sdk/src/call/raw.rs
- stylus-sdk/src/deploy/raw.rs
- stylus-sdk/src/storage/bytes.rs
- stylus-sdk/src/storage/cache.rs
- stylus-sdk/src/storage/eager.rs
- stylus-sdk/src/storage/map.rs
- stylus-sdk/src/storage/mod.rs
- stylus-sdk/src/storage/traits.rs
- stylus-sdk/src/storage/vec.rs
This PR applies a few refactors to enable a compilation mode without `StorageCache` and its `fnv` dependency.
When the default `storage-cache` feature is disabled, a new `EagerStorage` type becomes available for managing persistent state in the absence of caching. This reduces binary size for use cases where storage operations are rare, and allows for an eager style of programming.
Importantly, individual `StorageType` implementations may choose to do caching themselves. This is a reasonable tradeoff since it optimizes primitives without pulling in `fnv`.
Central to the implementation is a new `GlobalStorage` trait that both `EagerStorage` and `StorageCache` implement, reducing code duplication while using module-level cfg granularity.
> Disable storage cache

- Cargo.lock
- Cargo.toml
- stylus-proc/Cargo.toml
- stylus-proc/src/calls/mod.rs
- stylus-proc/src/lib.rs
- stylus-proc/src/methods/entrypoint.rs
- stylus-sdk/Cargo.toml
- stylus-sdk/src/abi/bytes.rs
- stylus-sdk/src/call/context.rs
- stylus-sdk/src/call/mod.rs
- stylus-sdk/src/call/raw.rs
- stylus-sdk/src/call/traits.rs
- stylus-sdk/src/call/transfer.rs
- stylus-sdk/src/deploy/raw.rs
- stylus-sdk/src/storage/mod.rs
Simplifies calls to other contracts by
- feature-gating all reentrancy behind the new `reentrant` flag
- a new `Call` type for making safe calls with doc examples
```rs
sol_interface! {
interface IService {
function makePayment(address user) payable returns (string);
}
}
pub fn do_call(account: IService, user: Address) -> Result<String, Error> {
let context = Call::new()
.gas(evm::gas_left() / 2)        // limit to half the gas left
.value(msg::value());            // set the callvalue
account.make_payment(context, user)  // note the snake case
}
```
> Simplify calls & condition reentrancy

- Cargo.lock
- Cargo.toml
- stylus-sdk/src/call/context.rs
- stylus-sdk/src/call/mod.rs
- stylus-sdk/src/call/raw.rs
- stylus-sdk/src/call/transfer.rs
- stylus-sdk/src/debug.rs
- stylus-sdk/src/deploy/raw.rs
- stylus-sdk/src/storage/vec.rs
Makes `Call::new` a compile error when used with the `reentrant` feature flag enabled. This is a sensible behavior given `new` is never correct in reentrant programming.
This is a minor but theoretically breaking change, so we'll bump the version number.
This PR makes other documentation improvements.
> Make `Call::new` a compile error in reentrant patterns

- stylus-proc/src/methods/external.rs
- stylus-proc/src/types.rs
This PR introduces configuration options for method selectors via the new `#[selector]` attribute.
```rs
impl Contract {
#[selector(name = "otherName")]
pub fn renamed() {
...
}
#[selector(id = "otherFunc(uint64)")]
pub fn other_selector(value: U64) {
...
}
#[selector(id = 0xba5eba11)]
pub fn exact_selector() {
...
}
```
```sh
$ cargo stylus export-abi
```
```solidity
/**
* This file was automatically generated by Stylus and represents a Rust program.
* For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
*/
interface IContract {
function otherName() external pure;
// note: selector was overridden to be 0x7cc01843.
function otherSelector(uint64 value) external pure;
// note: selector was overridden to be 0xba5eba11.
function exactSelector() …
```
> Configure selectors

- stylus-proc/src/types.rs
- stylus-sdk/src/types.rs
Fixes some minor edge cases in the SDK
Included is the new `Address::is_eoa` method for detecting if an account is an Externally Owned Account
```rs
let arbinaut = address!(361594F5429D23ECE0A88E4fBE529E1c49D524d8);
assert!(arbinaut.is_eoa());
assert!(!contract::address().is_eoa())
```
> Fix codehash for EOA's and `FixedBytes` in `sol_interface!`

- Cargo.lock
- Cargo.toml
- stylus-sdk/src/types.rs
This PR renames `is_eoa` to `has_code` for clarity around the constructor edge case in which the method will return false.
> Rename `is_eoa` to `has_code`

- stylus-sdk/src/storage/bytes.rs
Remove `mut` from `StorageString::get_string`
[DCO]: licenses/DCO.txt
[terms]: licenses/COPYRIGHT.md
> remove mut from StorageString::get_string

- Cargo.toml
- stylus-proc/src/methods/entrypoint.rs
Exports `main` in case the `entrypoint` macro is used in `lib.rs` :)
> Export main

- Cargo.lock
- Cargo.toml
- stylus-sdk/src/call/mod.rs
`delegate_call` was calling `RawCall::new_with_value` instead of `RawCall::new_delegate`
> Fix delegate_call

- .github/workflows/smoke-test.yml
- ci/smoke_test.sh
This PR sets the sepolia private key used for smoke tests as a CI env var using a repository secret instead of hardcoding one
> Set Sepolia Priv Key as CI Env Var

- stylus-sdk/src/evm.rs
- stylus-sdk/src/hostio.rs
- stylus-sdk/src/storage/map.rs
- stylus-sdk/src/types.rs
Associated PR: https://github.com/OffchainLabs/stylus/pull/191
> code, code_size hostios

- README.md
The cli tool is in another repository `https://github.com/OffchainLabs/cargo-stylus` so pointed the link there.
The previous relative url returned a 404 on github. 
Changed 
```md
see the [Cargo Stylus CLI Tool](CargoStylus)
```
to
```
see the [Cargo Stylus CLI Tool](https://github.com/OffchainLabs/cargo-stylus)
```
which is the url to the cargo stylus cli 
[DCO]: licenses/DCO.txt
[terms]: licenses/COPYRIGHT.md
> fix(readme): changes hyperlink to the CLI tool

- examples/erc20/Cargo.lock
- examples/erc20/Cargo.toml
- examples/erc20/src/erc20.rs
- examples/erc20/src/main.rs
- stylus-proc/src/methods/error.rs
- stylus-sdk/src/call/error.rs
- stylus-sdk/src/call/mod.rs
> SolidityError derives From<variant>

- stylus-proc/src/calls/mod.rs
We missed another spot where we have to use abi_decode_params with Alloy, leading to execution reverts when attempting to make external calls that return strings or bytes
> Use ABI Decode Params in Internal Call Return Data Parsing

- Cargo.toml
Without pinning alloy dependencies, cargo publish will attempt a refresh at the latest version possible for alloy. This prevents breaking changes
> Pin Alloy Dep to 0.7.6

- stylus-sdk/src/abi/bytes.rs
This pr add the support for converting `alloy_primitives::Bytes` to `stylus_sdk::Bytes` so user can easily handle some bytes-type values returned from alloy to what we support.
> feature: add support to convert from alloy_primitives::Bytes to stylus_sdk::Bytes

- stylus-sdk/src/abi/impls.rs
- stylus-sdk/src/abi/ints.rs
- stylus-sdk/src/abi/mod.rs
Support for alloy_primitives::Signed and alloy_primitives::Uint in return types and parameters.
Still in draft as I finish up the following tasks:
> Support for alloy_primitive int types

- stylus-proc/src/abi.rs
- stylus-proc/src/lib.rs
This allows usage of `#[derive(AbiType)]` within the `sol! {}` macro to support structs as return types. This should also apply to usage as parameters. I am curious about other use-cases such as structs defined outside of the `sol! {}` macro, and structs define in the `sol_storage! {}` macro.
> Simple derive macro for better struct support

- stylus-proc/src/lib.rs
- stylus-proc/src/types.rs
fixes #74
Allows references to structs within the `sol_interface!` macro. 
~Would like to consider what to do for paths containing the dot separator in solidity before merging.~
Path with separator will be unsupported for now. Added to docstring for clarity.
> Allow struct references within sol_interface macro

- stylus-proc/src/methods/external.rs
Ensure that selectors are unique. This prevents both unintentional function shadowing, as well as potentially malicious, intentional unreachable methods.
> Fail to build on duplicate selectors

- stylus-sdk/src/abi/ints.rs
Alloy 0.7.7 and the alloy_primitves int type changes were incompatible due to a trait const being added. Fixed by this PR.
> Fix SolType trait for ints in alloy 0.7.7

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> Add changelog and bump version numbers

- stylus-sdk/src/storage/bytes.rs
Fix storage of strings with length 32. Was previously treating these strings as short which would cause reading the root slot instead of the base slot.
> Fix off-by-one error when string len is 32

- stylus-sdk/src/abi/internal.rs
Fixes incorrect usage of alloy encoding for new alloy version
> Fix return encoding for sequence types

- README.md
Updates readme with links to OZ audit.
> Update README.md with OZ audit links

- Cargo.lock
- Cargo.toml
- stylus-proc/src/imports.rs
- stylus-proc/src/macros/entrypoint.rs
- stylus-proc/src/macros/public/export_abi.rs
- stylus-proc/src/macros/public/mod.rs
- stylus-proc/src/macros/public/types.rs
- stylus-sdk/src/abi/mod.rs
Fallback/receive support.
These functions currently support returning `ArbResult` and fallback always takes `calldata: &[u8]` as a parameter.
> Fallback receive

- Cargo.lock
- Cargo.toml
- examples/erc20/Cargo.lock
- examples/erc20/Cargo.toml
- examples/erc20/scripts/yarn.lock
- examples/erc721/Cargo.lock
- examples/erc721/Cargo.toml
- examples/erc721/scripts/yarn.lock
- examples/single_call/Cargo.lock
- examples/single_call/Cargo.toml
- examples/single_call/scripts/yarn.lock
Upgrade alloy to 0.8.13 and update examples.
This also fixes issue L-05 for the 0.7.0 sdk audit.
> Upgrade alloy to 0.8.13 and update examples

- Cargo.toml
- stylus-proc/src/macros/public/mod.rs
- stylus-proc/tests/fail/public/generated.stderr
Allows impl items that are not `const` inside `#[public]` macro.
> Allow impl items

- stylus-sdk/src/storage/mod.rs
- stylus-sdk/src/storage/traits.rs
Previousy it was possible to define storage for ints and uints which
whose bit size was not divisible by 8. This was both broken, and is not
intended as a supported feature of Stylus. This has been changed into a
compile-time error to avoid using these broken types.
This fixes issue C-01 from the OpenZeppelin 0.7.0 audit.
> Remove support for broken storage ints

- rust-toolchain.toml
- stylus-sdk/src/call/raw.rs
- stylus-sdk/src/hostio.rs
- stylus-sdk/src/storage/array.rs
- stylus-sdk/src/storage/bytes.rs
- stylus-sdk/src/storage/map.rs
- stylus-sdk/src/storage/mod.rs
- stylus-sdk/src/storage/vec.rs
**This PR allows the Stylus SDK to use Rust 1.83**
Currently, the Stylus SDK defines hostios via a macro called `wrap_hostio` which ends up producing two things:
1. A function that allows the user to conveniently call the hostio in more idiomatic, safe Rust, such as `fn base_fee(block_number: u64) -> U256`
2. A mutable static reference to a cache for recently called hostios. For instance, if the program recently called `base_fee()`, it will cache the result in a static variable called `BASE_FEE`
Today, this static variable is a mutable static reference to a struct called `CachedOption<T>`. It looks a bit like this:
```rust
pub(crate) static mut BASE_FEE: hostio::CachedOption<u64> = hostio::CachedOption::new(|| {
let mut data = ...
unsafe { hostio::base_fee(data.as_mut_ptr()) }; …
```
> Use Interior Mutability in Static References to Host I/O Caches

- stylus-sdk/Cargo.toml
- stylus-sdk/src/call/raw.rs
- stylus-sdk/src/deploy/raw.rs
- stylus-sdk/src/hostio.rs
Provides the default feature `hostio-caching` to `stylus-sdk`.
When disabled, any function that uses caching behavior to query a host node will stop doing so.
e.g. `msg::sender()` would query actual sender from host node each time (not just once), when `hostio-caching` feature disabled.
Extremely convenient for unit test mocks.
> feat: add hostio-caching feature

- stylus-proc/src/macros/public/types.rs
- stylus-sdk/src/abi/mod.rs
This PR allows the receive method to return an error, but maintains that the Ok result should be the unit type, as a receive function can never return an output argument
> Allow Receive Fn to Return Error

- Cargo.lock
- Cargo.toml
- examples/erc20/Cargo.lock
- examples/erc20/Cargo.toml
- examples/erc20/rust-toolchain.toml
- examples/erc721/Cargo.lock
- examples/erc721/Cargo.toml
- examples/erc721/rust-toolchain.toml
- examples/single_call/Cargo.toml
- examples/single_call/rust-toolchain.toml
- stylus-proc/src/macros/public/types.rs
- stylus-proc/src/macros/sol_interface.rs
- Use `abi_encode_params` instead of `abi_encode` inside sol interface macro.
- Update alloy libs 0.8.13 -> 0.8.14.
- Remove not used `stylus_sdk::abi::export`.
> fix: correct encoding in sol interface

- stylus-proc/src/macros/public/types.rs
This PR ensures that a fallback with no args is required to return Result<(), Vec<u8>> instead of Result<Vec<u8>, Vec<u8>> as its counterpart does
> Ensure Fallback No Args Returns Result with Unit Type OK

- stylus-proc/src/macros/sol_interface.rs
Make an external interface generated struct public. Otherwise, it won't be possible to put `sol_interface!` macro declaration into a separate module/file, like it was possible before.
> feat: allow pub item in sol interface

- stylus-sdk/src/host/mod.rs
- stylus-sdk/src/lib.rs
This PR defines a `Host` trait for the SDK, as we internally plan to move away from global hostio invocations and instead make it possible for Stylus programs to access a host environment via a `self.get_host()` method, making the SDK a lot simpler and clearer. Parametrizing contracts with a host trait allows developers to also mock the host trait for unit testing, enabling novel features such as support for new frameworks and potentially Anvil as a library.
This PR simply defines the host trait as a composition of various traits, and copies over the comments related to their hostios from src/hostios.rs.
Follow up is #200
> [1/5] - Define a Host Trait for the Stylus SDK

- stylus-sdk/src/host/mod.rs
- stylus-sdk/src/host/wasm.rs
Follow-up from #199, this PR defines a WasmHost implementation of the Host trait defined in #199. This WASM host will be used by Stylus contracts when they are built for a WASM target. Underneath the hood, they still just invoke the current global hostios that are present in the SDK for simplicity. In the future, global hostios will be deprecated, then moved into the WasmHost implementation.
> [2/5] - Define Initial WasmHost Implementation for Wasm Targets

- stylus-proc/src/consts.rs
- stylus-proc/src/lib.rs
- stylus-proc/src/macros/derive/erase.rs
- stylus-proc/src/macros/entrypoint.rs
- stylus-proc/src/macros/sol_storage/mod.rs
- stylus-proc/src/macros/storage.rs
- stylus-proc/tests/derive_erase.rs
- stylus-sdk/src/abi/mod.rs
- stylus-sdk/src/host/mod.rs
- stylus-sdk/src/prelude.rs
- stylus-sdk/src/storage/array.rs
- stylus-sdk/src/storage/bytes.rs
- stylus-sdk/src/storage/map.rs
- stylus-sdk/src/storage/mod.rs
- stylus-sdk/src/storage/traits.rs
- stylus-sdk/src/storage/vec.rs
This PR follows https://github.com/OffchainLabs/stylus-sdk-rs/pull/200 by adding a host parameter to the StorageType `new` function, and therefore, to all core storage types and contracts in the Stylus SDK. the Router entrypoint now also requires a host as a parameter.
This PR also modifies the stylus-proc crate to generate code that includes a raw pointer to a host in contracts, and implements the Stylus entrypoint by initializing the default implementation of the host trait, the WasmHost.
This PR adds a __stylus_host: *const H field to all storage types, and the proc macro for top-level storage adds it to contracts.
Hello world remains the same
> [3/5] - Use a Boxed, Dyn Host Trait for Contract Initialization

- stylus-sdk/src/storage/bytes.rs
When the storage bytes has length 32, it loses data when setting the length to a smaller value because it doesn't move the data correctly.
> Fix storage bytes set-len when shrinking

- stylus-sdk/src/storage/bytes.rs
Add unit tests to the StorageBytes structure. Theses tests will ensure we don't break StorageBytes when changing the implementation. These changes will be introduced in a following PR.
> Add unit tests to storage bytes

- stylus-core/src/host.rs
- stylus-core/src/lib.rs
- stylus-sdk/src/evm.rs
- stylus-sdk/src/host/mod.rs
- stylus-test/src/mock.rs
This PR adds missing host methods and `gas_to_ink` to the host trait
> [8] - Add Missing Methods to Host Trait

- stylus-core/src/host.rs
- stylus-proc/src/macros/public/types.rs
- stylus-proc/src/macros/storage.rs
- stylus-proc/tests/derive_erase.rs
- stylus-sdk/src/abi/internal.rs
- stylus-sdk/src/abi/mod.rs
After this PR, the code impact of the `Host` trait addition on contracts is only 0.1Kb compared to the code from 0.7.0.
Using global functions that take in a &dyn Trait has a massive impact on WASM size, compared to instead implementing the method as a trait on your contract. Here’s the context:
We have a Contract struct in Rust, and we have a Router trait we are required to implement. Looks a bit like this today:
We route each selector to a specific method of our contract struct, and before that, we check if we need to deny non-payable functions that have a tx with a value
The problem is this deny_value method takes in a &dyn Host, which requires the compiler to produce more data to resolve vtables
We fixed this by instead defining a ValueDenier trait that contracts implement, so there …
> Reduce Wasm Code Size Impact of Host Trait

- examples/erc20/Cargo.lock
- examples/erc20/Cargo.toml
- examples/erc20/src/main.rs
- examples/erc721/Cargo.lock
- examples/erc721/Cargo.toml
- examples/erc721/src/main.rs
- examples/single_call/Cargo.lock
- examples/single_call/Cargo.toml
- examples/single_call/src/lib.rs
- stylus-core/src/lib.rs
- stylus-sdk/Cargo.toml
- stylus-sdk/src/call/mod.rs
- stylus-sdk/src/host/calls.rs
- stylus-sdk/src/lib.rs
- stylus-sdk/src/storage/vec.rs
- stylus-test/src/vm.rs
This PR fixes a few issues in the main branch.
> Fix examples and doctest

- Cargo.lock
- stylus-proc/Cargo.toml
- stylus-proc/src/macros/entrypoint.rs
- stylus-proc/src/macros/storage.rs
- stylus-sdk/Cargo.toml
- stylus-sdk/src/host/mod.rs
- stylus-sdk/src/lib.rs
- stylus-sdk/src/storage/array.rs
- stylus-sdk/src/storage/bytes.rs
- stylus-sdk/src/storage/map.rs
- stylus-sdk/src/storage/mod.rs
- stylus-sdk/src/storage/vec.rs
This PR fixes cargo stylus replay after the release of 0.8.0. It adds a new feature flag to enable the TestVM mock instead of relying on the target architecture. It also removes an unnecessary call to `pay_for_memory_grow`, which caused a divergence between the trace and execution in previous versions of Nitro.
Close https://linear.app/offchain-labs/issue/STY-230
> Fix Cargo Stylus Replay

- CHANGELOG.md
- stylus-sdk/src/lib.rs
And also fix the CHANGELOG. When we are ready to release, we should update it with the correct date.
> Add custom error when stylus-test is enabled for wasm32

- stylus-sdk/src/storage/mod.rs
We need this to implement [Erc721Consecutive](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/9e840ca53c21a68e0878aaa4bbffac08234f853e/contracts/src/token/erc721/extensions/consecutive.rs#L50) and [Erc2981](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/9e840ca53c21a68e0878aaa4bbffac08234f853e/contracts/src/token/common/erc2981.rs#L37)
> add `StorageU96` int alias

- stylus-sdk/Cargo.toml
- stylus-sdk/src/block.rs
- stylus-sdk/src/call/raw.rs
- stylus-sdk/src/contract.rs
- stylus-sdk/src/deploy/raw.rs
- stylus-sdk/src/hostio.rs
- stylus-sdk/src/msg.rs
- stylus-sdk/src/tx.rs
Removing this feature reduces the contract binary size and the gas usage when the cache is not hit. The caching added an overhead that required it to hit dozens of times to be worth it.
Users are advised to add caching in the form of local variables if the contract calls the same HostIO multiple times.
Close [STY-235](https://linear.app/offchain-labs/issue/STY-235)
> Remove the HostIO-caching feature

- stylus-test/README.md
This PR adds a basic README to Stylus Test, which serves as a nice overview in docs.rs and is similar in nature to the inline comments. However, this README is helpful in that it explains the examples of the TestVM usage along with info about how to include it in your project
> Add a README to Stylus Test

- stylus-proc/src/macros/public/mod.rs
- stylus-proc/tests/fail/public/constructor.rs
- stylus-proc/tests/fail/public/constructor.stderr
Check whether the function with a special name has a matching attribute. This ensures there isn't a routing conflict that could be exploited.
Close STY-254
Close M-03
> Be more strict with special function names

- mini-alloc/src/imp.rs
- stylus-core/src/calls/mod.rs
- stylus-core/src/deploy.rs
- stylus-core/src/lib.rs
These changes ensure that `stylus_core` no longer uses std, though without a check for `export-abi`, which I assume is not needed in this code. It also enables a lint for `mini-alloc` that prevents a message about discouraged use of mutable statics.
> Don't use std for stylus-core, lint to ignore alloc_impl unsafe

- stylus-sdk/src/hostio.rs
The stylus-test feature does not support mocking the HostIO functions directly. Instead, the developer should use the TestVM infrastructure. The panic will clarify why the tests are not working as expected.
Close STY-258
> Panic when using HostIOs with stylus test

- stylus-proc/src/macros/public/types.rs
- stylus-proc/tests/public_composition.rs
We have gone through several iterations of how fallbacks and receives should work in the SDK, and now that we have composition-based inheritance, we have decided that we want to simplify the semantics drastically.
We have removed any kind of inheritance for fallback and receive methods. Instead, only the ones defined the contract will be used. If they are not defined, default fallback and receive methods are included in the generated code for a contract entrypoint.
We believe this improves the SDK's simplicity and auditability of contracts, as inheritance with fallbacks becomes quite complex. Even though this does not match Solidity semantics one to one, we believe this makes our system a lot simpler in this regard.
> Simplify Fallback/Receive Semantics

- stylus-proc/src/macros/public/mod.rs
- stylus-proc/src/macros/public/types.rs
It works great with the new inheritance model and is necessary for good developer experience.
Without this support, it would be impossible to inherit contracts that return specific error enums, so devs (our OZ library included) would have to rely on plain `Vec<u8>` for errors.
> feat: Add Support for Associated Types in Contracts

- stylus-proc/src/macros/public/mod.rs
- stylus-proc/tests/fail/public/constructor.rs
- stylus-proc/tests/fail/public/constructor.stderr
Ensure the override is not converted into camelCase. Previously, the override set to tokenURI became tokenUri. Also, add some unit tests to ensure this doesn't happen again.
Close STY-266
> Fix selector override in public proc macro

- .github/workflows/integration.yml
- Cargo.lock
- Cargo.toml
- ci/build_and_test.sh
- ci/integration_test.sh
- stylus-tools/Cargo.toml
- stylus-tools/src/devnet.rs
- stylus-tools/src/lib.rs
The Node struct in the devnet module provides a way to start a full
Nitro node in the background. We use the crate testcontainers to start
the node with Docker. This functionality allows us to implement
integration tests for Stylus contracts.
> [Integration Test] Add dev node to stylus tools

- stylus-tools/src/cargo_stylus.rs
Remove the experimental prefix from the constructor-related arguments.
> Update Cargo Stylus usage in stylus-tools

- stylus-sdk/src/storage/mod.rs
Add some integer functions to add to, subtract, or divide from the underlying storage units.
In my opinion, it's better to add some extra functions to do this, even if the team has made a conscious decision to require the end user to make any modifications to storage values before doing the setting. This is just too common of a pattern, and using nested storage values is a huge pain with a get, add, then set, due to Rust making sure the value isn't dropped midway. Having a simple setter that adds, multiplies, divides, etc, will improve this experience.
> Add some helper functions to make integer setting easier

- .cargo/audit.toml
This fixes the reporting of RUSTSEC-2021-0131 by cargo audit.
> Add explanation of why our brotli2 usage is safe.

- ci/build_and_test.sh
Run trybuild tests without other features enabled to get standardized error messages.
> Fix trybuild tests

- stylus-proc/src/macros/public/mod.rs
- stylus-proc/tests/fail/public/constructor.rs
- stylus-proc/tests/fail/public/constructor.stderr
Resolves NIT-3745
Don't allow selector override to use stylus_constructor.
> Don't allow selector override to use stylus_constructor

- stylus-sdk/src/abi/export/mod.rs
Resolves NIT-3744
Underscore bytes in export-abi generation
> Underscore bytes in export-abi generation

- examples/callee/src/lib.rs
- examples/caller/src/lib.rs
- examples/erc20/src/ierc20.rs
- examples/erc721/src/ierc721.rs
- examples/inheritance/src/lib.rs
- stylus-proc/src/macros/public/export_abi.rs
- stylus-proc/src/macros/public/mod.rs
- stylus-proc/src/macros/public/types.rs
- stylus-proc/src/types.rs
- stylus-proc/src/utils/mod.rs
- stylus-proc/tests/fail/public/missing_macros.rs
- stylus-proc/tests/fail/public/missing_macros.stderr
- stylus-proc/tests/parameterized_trait_with_associated_types.rs
- stylus-proc/tests/public.rs
- stylus-proc/tests/public_composition.rs
Resolves NIT-3844
This PR proposes that the #[public] macro becomes a requirement for pub traits implemented by the entrypoint struct.
This will enable to: 
- Enforce that pub traits have associated types bounded to AbiType, [here](https://github.com/OffchainLabs/stylus-sdk-rs/blob/9e514963d0931257c09219e5d98a205f79b979b7/examples/callee/src/lib.rs#L26) is an example.
- Overwrite the pub trait in case the contract-client-gen feature is provided. Today caller contracts need to import generated traits, such as [Trait1ContractClientGen](https://github.com/OffchainLabs/stylus-sdk-rs/blob/9e514963d0931257c09219e5d98a205f79b979b7/examples/caller/src/lib.rs#L8,), that don't have the same name as the original pub trait, Trait1 in this example. By overwriting the pub trait, the caller contract …
> Public macro related to trait
