README.md

There was a missing "be" so I fixed the grammar in this sentence.

docs: improve grammar

---

Cargo.lock
Cargo.toml
stylus-sdk/Cargo.toml

Enables all feature flags in docs.rs

Enable all feature flags for docs.rs

---

.clabot
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
README.md
licenses/COPYRIGHT.md
licenses/DCO.txt

Updates the overview and gentle intro link

Tweak Readme and add DCO

---

stylus-sdk/src/evm.rs

[DCO]: licenses/DCO.txt
[terms]: licenses/COPYRIGHT.md

Set proper doc link

---

examples/single_call/README.md

Fix SingleCall README link

---

Cargo.toml

Bump Version of Stylus Proc

---

Cargo.lock
Cargo.toml
stylus-proc/src/calls/mod.rs
stylus-sdk/src/abi/bytes.rs

Small change required in some trait impls. Should not be user-impacting.

Upgrade to alloy 0.7.7, required for upcoming work

---

stylus-proc/src/calls/mod.rs

Use correct encoding method

---

Cargo.lock
Cargo.toml
stylus-proc/src/types.rs
stylus-proc/tests/fail/public/generated.stderr

Fix failing unit tests and bump version for beta release

Bump versions for beta release and fix tests

---

Cargo.lock
Cargo.toml

increment version number for 0.7.0-beta.1

---

stylus-proc/src/macros/public/types.rs
stylus-sdk/src/abi/mod.rs

Allow Receive Fn to Return Err

---

CHANGELOG.md

Add changelog for 0.7.0 release.

Add changelog for 0.7.0

---

Cargo.lock
Cargo.toml
stylus-sdk/Cargo.toml
stylus-sdk/src/call/mod.rs
stylus-sdk/src/call/raw.rs
stylus-sdk/src/call/transfer.rs
stylus-sdk/src/host/calls.rs
stylus-sdk/src/host/mod.rs
stylus-sdk/src/lib.rs
stylus-test/src/vm.rs

This PR is a release candidate for 0.8.0 of the Stylus SDK, including a brand new test framework that has significant changes to the internals of how hostios are accessed, and deprecates all global hostio invocations, even those from global methods such as `msg::sender()`.
This PR is pending more testing of different Stylus examples and ecosystem projects to ensure no breaking changes were introduced.

v0.8.0 Release Candidate

---

stylus-sdk/src/storage/array.rs
stylus-sdk/src/storage/bytes.rs
stylus-sdk/src/storage/map.rs
stylus-sdk/src/storage/mod.rs
stylus-sdk/src/storage/vec.rs

Fix fmt issue detected in https://github.com/OffchainLabs/nitro/pull/2965
related to NIT-3046

Fix formatting

---

stylus-proc/src/macros/public/attrs.rs
stylus-proc/src/macros/public/mod.rs
stylus-proc/src/macros/public/types.rs
stylus-proc/tests/public_composition.rs
stylus-sdk/src/abi/mod.rs

First pass implementation of composition/trait based inheritance. Includes an example test which shows usage.

first pass implementation of trait based inheritance

---

CHANGELOG.md
Cargo.lock
Cargo.toml
stylus-proc/Cargo.toml
stylus-proc/src/macros/entrypoint.rs
stylus-proc/src/macros/storage.rs
stylus-sdk/Cargo.toml

This PR should fix the issue with https://github.com/OpenZeppelin/rust-contracts-stylus/pull/601. I will create a release candidate so we can test before making a release.

Fix wasm32 dependencies

---

CHANGELOG.md
Cargo.lock
Cargo.toml
stylus-proc/Cargo.toml
stylus-proc/src/macros/entrypoint.rs
stylus-proc/src/macros/storage.rs
stylus-sdk/Cargo.toml
stylus-sdk/src/lib.rs

Port of the changes of 0.8.3 to main

Port 0.8.3 changes to main

---

stylus-proc/src/lib.rs

Add documentation for constructors

---

stylus-sdk/src/abi/mod.rs

Improve the fallback documentation to clarify the relationship with receive.

Improve fallback function documentation

---

examples/erc721/src/erc721.rs
stylus-proc/src/macros/sol_storage/proc.rs

Resolves NIT-3741
Support mapping with names in sol_storage.

Support mapping with names in sol_storage
